name: Building Blocks

on: workflow_dispatch
jobs:
    echo-hello:
        runs-on: ubuntu-Latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"
    echo-goodbye:
        runs-on: ubuntu-Latest
        steps:
            - name: Failed Step
              run: |
                echo "This step is designed to fail"
            - name: Say Goodbye
              run: echo "Goodbye, World!"

          