name: The release watcher

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 9 * * 1'  # on every monday at 9:00 AM
    workflow_dispatch:

jobs:
    watch:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Workflow triggered by a(n) ${{ github.event_name }} event."
            - name: Current date and time
              run: echo "Current date and time $(date)"
            - name: Completed
              run: echo "Release watcher completed"




